### PR TITLE
Using [NotNull]

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@Eilon Can you merge this fix like the other repos?

**Comment by Eilon** [comment]
@Tratcher correct me if I'm wrong, this is a temporary repo that we plan to delete once NCL is up and running, right?

**Comment by Tratcher** [comment]
"Temporary" until there is a viable HttpClient for CoreCLR, yes. On Windows we've seen reasonable progress in this space, but there hasn't been any progress for Linux/Mac.

**Comment by Eilon** [comment]
Ok then I think we don't need this PR then because this isn't meant to be long-term code really.

**Comment by hishamco** [comment]
Thanks for clarification

**Pull request closed without merging**
