### PR TITLE
Update README.md and build scripts

### PR DESCRIPTION
**Pull request by natemcmaster**

### CODE REVIEW

**Comment by Tratcher** [comment]
No, this repo is obsolete.

**Comment by natemcmaster** [comment]
Can we remove? If not, at least turn off CI (travis and/or TC).

cc: @Eilon

**Comment by Eilon** [comment]
Discussed in person, it's disabled on Travis.

@pranavkm can we just delete this config on aspnetci?

**Comment by pranavkm** [comment]
Removed from the CI.

**Pull request closed without merging**
