### PR TITLE
Fix inadvertent infinite loop in ApmStreamWrapper

### PR DESCRIPTION
**Pull request by JesperTreetop**
This looked like it would recurse and was meant to be called on the _innerStream like everything else.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@JesperTreetop__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by davidfowl** [comment]
LGTM

**Comment by JesperTreetop** [comment]
Awesome. Shouldn't there be a Roslyn Analyzer that checks for this kind of stuff?

**Comment by davidfowl** [comment]
Sure?

**Comment by davidfowl** [comment]
Or a better unit test

**Pull request merged**
